on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2        

    - name: Add and Commit changes to main branch
      run: |
        git add assets/css/*
        git commit -m 'Updates compiled CSS files'

    - name: 📂 Sync files
      uses: on@4SamKirkland/FTP-Deploy-Acti.3.0
      with:
        server: 139.99.99.156
        username: admin_ZAcademy_github@devweb5s.site
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wp-content/themes/khoahoc/


