on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: assets/sass/style.scss
          destination: assets/css/style.css
    
    - name: 📂 Sync files
      uses: on@4SamKirkland/FTP-Deploy-Acti.3.0
      with:
        server: 139.99.99.156
        username: admin_ZAcademy_github@devweb5s.site
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wp-content/themes/khoahoc/


